file-version: 5
# Dispensables by TrueProtocol
# Support Discord: https://discord.com/invite/HeknxrbXHn

# Dispensers Section
dispensers:
  # Enables dispensers to be affected
  # Set to false if you wish for dispensers to be unaffected
  enabled: true
  # Toggles whether the 'items' and list is a blacklist or a whitelist
  # true - 'items' acts as a whitelist
  # false - 'items' acts as a blacklist
  whitelist-mode: false
  # Amount to dispense if not defined in 'items' OR if 'whitelist-mode' is false
  default-amount: 1
  # Items affected
  # NOTE: You can remove any value in each entry. If the attribute is not listed, the plugin will not check for it.
  # Valid Attributes: material, display-name, lore, enchantments, amount
  items:
    '1': # You can name this whatever you want
      material: WOODEN_SWORD
      display-name: Wooden Sword
      lore:
        - Line 1
        - Line 2
      enchantments:
        SHARPNESS: 1
        UNBREAKING: 3
      amount: 1
    '2':
      material: TNT

# Droppers Section
droppers:
  # Enables droppers to be affected
  # Set to false if you wish for droppers to be unaffected
  enabled: true
  # Toggles whether the 'items' and list is a blacklist or a whitelist
  # true - 'items' acts as a whitelist
  # false - 'items' acts as a blacklist
  whitelist-mode: true
  # Amount to drop if not defined in 'items' OR if 'whitelist-mode' is false
  default-amount: 1
  # Items affected
  # NOTE: You can remove any value in each entry. If the attribute is not listed, the plugin will not check for it.
  # Valid Attributes: material, display-name, lore, enchantments, amount
  items:
    '1': # You can name this whatever you want
      material: WOODEN_SWORD
      display-name: Wooden Sword
      lore:
        - A basic wooden sword.
      enchantments:
        SHARPNESS: 1
      amount: 1
    '2':
      material: DIAMOND
      amount: 5

# Hoppers Section
hoppers:
  # Enables hoppers to be affected
  # Set to false if you wish for hoppers to be unaffected
  enabled: true
  # Toggles whether the 'items' and list is a blacklist or a whitelist
  # true - 'items' acts as a whitelist
  # false - 'items' acts as a blacklist
  whitelist-mode: false
  # Amount to hop if not defined in 'items' OR if 'whitelist-mode' is false
  default-amount: 10
  # Items affected
  # NOTE: You can remove any value in each entry. If the attribute is not listed, the plugin will not check for it.
  # Valid Attributes: material, display-name, lore, enchantments, amount
  items:
    '1': # You can name this whatever you want
      material: WOODEN_SWORD
      display-name: Wooden Sword
      lore:
        - A basic wooden sword.
      enchantments:
        SHARPNESS: 1
      amount: 1
    '2':
      material: DIAMOND