name: Sortify
version: '${project.version}'
main: me.trueprotocol.sortify.Sortify
api-version: 1.19
authors: [ TrueProtocol ]
description: Control what comes out of your dispensers!
commands:
  sortify:
    description: Main command for Sortify!
    usage: /<command>
    aliases: [ sort ]
    permission: sortify.admin
  dispenser:
    description: Command to control dispensers.
    usage: /<command>
    aliases: [ disp ]
    permission: sortify.dispensers
  dropper:
    description: Command to control droppers.
    usage: /<command>
    aliases: [ drop ]
    permission: sortify.droppers
  hopper:
    description: Command to control droppers.
    usage: /<command>
    aliases: [ hop ]
    permission: sortify.hoppers